# 定义array数组

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

np.array(,dtype=类型)  
int64/32... 整形 float64/32... 浮点型  
位数越大精度越高

In [4]:
a = np.array([2,3,4], dtype=np.int64)
a,a.dtype

(array([2, 3, 4]), dtype('int64'))

In [5]:
a = np.array([2,3,4], dtype=np.int32)
a,a.dtype

(array([2, 3, 4], dtype=int32), dtype('int32'))

In [6]:
a = np.array([2,3,4], dtype=np.float64)
a,a.dtype

(array([2., 3., 4.]), dtype('float64'))

# 二维/多维

普通定义

In [7]:
a = np.array([[1,2,3],
              [2,3,4]])

In [8]:
a

array([[1, 2, 3],
       [2, 3, 4]])

0数组定义  
np.zeros((行,列))  

In [9]:
a = np.zeros((2,3))

In [10]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

1  
np.ones()

In [11]:
a = np.ones((2,3),dtype=np.int16)

In [12]:
a,a.dtype

(array([[1, 1, 1],
        [1, 1, 1]], dtype=int16),
 dtype('int16'))

无  
np.empty()

In [13]:
a = np.empty((2,3))

In [14]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

有序数列  
np.arange()  类似range函数

In [15]:
a = np.arange(10,20,2)

In [16]:
a

array([10, 12, 14, 16, 18])

reshape 重新定义行列

In [17]:
a = np.arange(12).reshape(3,4)

In [18]:
a = np.arange(12)
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

np.linspace(始,终,个数) 生成等间隔数

In [19]:
a = np.linspace(1,10,6)

In [20]:
a

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [21]:
a.reshape(2,3)

array([[ 1. ,  2.8,  4.6],
       [ 6.4,  8.2, 10. ]])