# 基础运算

加法 +

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])

In [3]:
b = np .arange(1,5)

In [4]:
b

array([1, 2, 3, 4])

In [5]:
a+2

array([3, 4, 5, 6])

In [6]:
a+b

array([2, 4, 6, 8])

减法 -

In [7]:
a-b

array([0, 0, 0, 0])

乘法 *

In [8]:
a*b

array([ 1,  4,  9, 16])

除法 /

In [9]:
a/b

array([1., 1., 1., 1.])

乘方 **

In [10]:
a**2

array([ 1,  4,  9, 16])

In [11]:
a**b

array([  1,   4,  27, 256])

三角函数  
np.sin(*) cos tan

In [12]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [13]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [14]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

比值 返回True False

In [15]:
a,a<3

(array([1, 2, 3, 4]), array([ True,  True, False, False]))

In [16]:
a,a==2,a!=2

(array([1, 2, 3, 4]),
 array([False,  True, False, False]),
 array([ True, False,  True,  True]))

# 二维运算

In [17]:
a = np.array([[1,2],[2,3]])

In [18]:
b = np.arange(4).reshape((2,2))

In [19]:
a,b

(array([[1, 2],
        [2, 3]]),
 array([[0, 1],
        [2, 3]]))

乘法

元素逐个相乘  
a11\*b11 a12\*b12...

In [20]:
a*b

array([[0, 2],
       [4, 9]])

矩阵乘法  
前行*后列

In [21]:
a@b

array([[ 4,  7],
       [ 6, 11]])

In [22]:
np.dot(a,b)

array([[ 4,  7],
       [ 6, 11]])

In [23]:
a.dot(b)

array([[ 4,  7],
       [ 6, 11]])

In [43]:
a = np.random.random((2,3))  
#随机生成二行三列的数组

In [33]:
a

array([[0.01780696, 0.65262751, 0.65512505],
       [0.8069919 , 0.86877267, 0.66269096]])

求和 np.sum()

In [44]:
np.sum(a),np.min(a),np.max(a)

(np.float64(3.545596587585504),
 np.float64(0.0023189567630351737),
 np.float64(0.9829636588913746))

最小值 np,.min()

最大值 np.max()

axis 1 每行  0 每列  
事例二行三列   
=1 输出两个元素 =0 输出三个元素

In [37]:
np.sum(a,axis=1),np.sum(a,axis=0)

(array([1.32555953, 2.33845554]), array([0.82479886, 1.52140018, 1.31781602]))

In [38]:
np.min(a,axis=1),np.min(a,axis=0)

(array([0.01780696, 0.66269096]), array([0.01780696, 0.65262751, 0.65512505]))

In [39]:
np.max(a,axis=1),np.max(a,axis=0)

(array([0.65512505, 0.86877267]), array([0.8069919 , 0.86877267, 0.66269096]))