# 基础运算

In [1]:
import numpy as np

In [2]:
a = np.arange(2,14).reshape((3,4))

In [3]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

位置索引  0-(n-1)

In [4]:
np.argmin(a),np.argmax(a)

(np.int64(0), np.int64(11))

平均值 mean()

In [5]:
np.mean(a)

np.float64(7.5)

In [6]:
a.mean()

np.float64(7.5)

In [7]:
np.mean(a,axis=1),np.mean(a,axis=0)

(array([ 3.5,  7.5, 11.5]), array([6., 7., 8., 9.]))

加权平均数 average(,weights=权重)

In [8]:
n = np.random.random((3,4))

In [9]:
n

array([[0.45003756, 0.43467882, 0.53443184, 0.57181423],
       [0.57606376, 0.33675864, 0.68856658, 0.33675619],
       [0.66065904, 0.83824333, 0.72442625, 0.57937821]])

In [10]:
np.average(a,weights=n)

np.float64(7.963119101348203)

In [11]:
np.average(a,weights=n,axis=0),np.average(a,weights=n,axis=1)

(array([6.49946983, 8.00284357, 8.39024753, 9.02033397]),
 array([ 3.61679855,  7.40555022, 11.4361939 ]))

中位数 np.median()

In [12]:
np.median(a)

np.float64(7.5)

In [13]:
np.median(a,axis=1),np.median(a,axis=0)

(array([ 3.5,  7.5, 11.5]), array([6., 7., 8., 9.]))

累加 np.cumsum()  
[1,1+2,1+2+3,...]

In [14]:
np.cumsum(a)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54, 65, 77, 90])

In [15]:
np.cumsum(a,axis=1),np.cumsum(a,axis=0)

(array([[ 2,  5,  9, 14],
        [ 6, 13, 21, 30],
        [10, 21, 33, 46]]),
 array([[ 2,  3,  4,  5],
        [ 8, 10, 12, 14],
        [18, 21, 24, 27]]))

累差 np.diff  
逐行单独计算

In [16]:
np.diff(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.diff(a,axis=1),np.diff(a,axis=0)

(array([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]),
 array([[4, 4, 4, 4],
        [4, 4, 4, 4]]))

非零 np.nonzero()  
返回非零索引值

In [18]:
np.nonzero(a) 

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

排序 np.sort()  
逐行单独计算

In [19]:
a = np.arange(14,2,-1).reshape(3,4)

In [20]:
np.sort(a)

array([[11, 12, 13, 14],
       [ 7,  8,  9, 10],
       [ 3,  4,  5,  6]])

矩阵转置

In [21]:
np.transpose(a)

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [22]:
a.T

array([[14, 10,  6],
       [13,  9,  5],
       [12,  8,  4],
       [11,  7,  3]])

In [23]:
a.T@a

array([[332, 302, 272, 242],
       [302, 275, 248, 221],
       [272, 248, 224, 200],
       [242, 221, 200, 179]])

截取 np.clip(,最大,最小)

In [24]:
np.clip(a,5,9)

array([[9, 9, 9, 9],
       [9, 9, 8, 7],
       [6, 5, 5, 5]])